import type { Metadata } from "next";
import Link from "next/link";
import { BeforeAfterWorkflow, PlatformHeroPreview, PlatformScreenGallery, ProductWorkflowDemo } from "../components/PlatformProductExperience";
import { Page, SectionIntro } from "../components/SiteShell";
import { products } from "../data/products";
import { DEFAULT_LOCALE, localePath, type Locale } from "../i18n/config";
import { ProductMaturityBadge, ProductMaturityLegend } from "../components/Governance";

export const metadata: Metadata = { title: "Property Workflow Products & Operating System | REOS", description: "Explore governed REOS property workflow products across the development lifecycle." };

const lifecycle = [
  ["01", "Plot", "Development", "Establish land and ownership context", "Land and authority records"], ["02", "Project", "Development", "Coordinate readiness and approvals", "Project and planning systems"],
  ["03", "Unit", "Development", "Create the controlled unit record", "Development systems"], ["04", "Sales", "Commercial", "Connect buyer, unit, terms and evidence", "CRM and sales systems"],
  ["05", "Handover", "Customer operations", "Prepare inspection, evidence and acceptance", "Handover systems"], ["06", "Title Deed", "Registration", "Prepare registration-ready evidence", "Authorized registry"],
  ["07", "NOC", "Approvals", "Resolve prerequisites and issuer requirements", "Authorized issuer"], ["08", "Resale", "Transactions", "Coordinate ownership and clearance readiness", "Transaction systems"],
  ["09", "Cancellation", "Commercial governance", "Control approvals, refunds and inventory release", "Finance and sales systems"], ["10", "Operations", "Community operations", "Connect service, occupancy and asset context", "Property systems"],
] as const;

const plannedProducts = [
  ["03", "Unit Cancellation", "Sales & inventory", "Govern ownership reversals, cancellations and settlements using controlled workflows.", "Developers · Finance · Sales operations", "Compliance checks · Financial approvals · Authority coordination · Exception handling"],
  ["04", "Customer Handover", "Customer operations", "Streamline customer onboarding, inspection, snagging, acceptance and unit handover.", "Developers · Owners · Community operators", "Inspection readiness · Snagging · Customer acceptance · Key release"],
  ["05", "AI Document Intelligence", "Evidence readiness", "Extract, validate and govern documents using planned AI-assisted controls.", "Operations · Reviewers · Compliance teams", "Classification · Extraction · Completeness review · Exception guidance"],
  ["06", "Enterprise Integration Hub", "Orchestration", "Connect approved enterprise, authority and third-party systems through validated interfaces.", "Enterprise IT · Operations · Authorized parties", "Planned adapters · Case synchronization · Boundary controls · Integration monitoring"],
] as const;

const stakeholderValue = [
  ["Developers", "Fragmented project-to-customer handoffs", "Coordinate lifecycle cases", "More accountable delivery"],
  ["Sales teams", "Customer and unit status live in separate views", "Connect sales actions to case readiness", "Clearer transaction progress"],
  ["CRM teams", "Follow-up depends on manual status chasing", "Expose the current owner and next action", "More consistent customer service"],
  ["Customer care", "Customers receive incomplete progress context", "Share governed milestones and requirements", "Better-informed conversations"],
  ["Finance", "Refunds and clearances are disconnected from workflow", "Connect financial review to the case", "Controlled commercial decisions"],
  ["Legal", "Authority and evidence context is difficult to reconstruct", "Preserve versions, approvals and boundaries", "Stronger reviewability"],
  ["Property management", "Handover and operating records arrive late", "Prepare operational context earlier", "Smoother operational readiness"],
  ["Authorities", "Submissions can be unstructured or incomplete", "Prepare clearer, traceable case context", "Better submission readiness"],
  ["Property owners", "Progress and responsibilities are unclear", "Provide a guided, visible case journey", "Greater service clarity"],
  ["Investors", "Portfolio context is spread across teams", "Present governed operational visibility", "More informed oversight"],
] as const;

const fragmentation = ["Email chains", "Excel trackers", "Manual approvals", "Missing visibility", "Disconnected systems", "Delayed NOCs", "Delayed title deeds", "Customer frustration"] as const;
const governance = [["01", "Policy enforcement", "Workflow rules applied within the agreed scope"], ["02", "Approval matrix", "Defined reviewers, approvers and handoffs"], ["03", "Authority controls", "Explicit decision and system boundaries"], ["04", "Compliance rules", "Required checks connected to workflow"], ["05", "Exception monitoring", "Incomplete and blocked cases made visible"], ["06", "Risk controls", "Sensitive actions kept within authorized roles"], ["07", "Audit trails", "Versions, actions and decisions preserved"]] as const;
const outcomes = [["Title deed readiness", "Prepare evidence and ownership actions through one controlled case."], ["NOC readiness", "Make prerequisites, issuer context and outstanding actions visible."], ["Customer experience", "Give service teams clearer milestones and next actions."], ["Operational visibility", "See case state, dependencies and responsibility across participants."], ["Reduced manual coordination", "Replace avoidable status chasing with guided workflow context."], ["Governed transactions", "Keep reviews and decisions connected to supporting evidence."], ["Reduced operational risk", "Surface exceptions and boundaries before work progresses."], ["Business scalability", "Apply one operating model across additional governed workflows."]] as const;

export function View({ locale = DEFAULT_LOCALE }: { locale?: Locale }) {
  const L = (path: string) => localePath(locale, path);
  const productAccess = products.map((product) => ({ ...product, accessHref: L(`/platform/products/${product.slug}/login`) }));
  return <Page className="inner-page" locale={locale}>
    <section className="sales-hero platform-commercial-hero"><div className="sales-hero-copy"><span className="eyebrow">REOS PRODUCT PLATFORM · B2B · B2G · B2C</span><h1>The Operating System<br /><em>for Property Development.</em></h1><p>Automate property workflows from plot creation through title deed issuance, NOC management, ownership changes and customer handover—within one governed operating model.</p><div className="hero-actions"><Link className="button gold" href={L("/demo")}>Request a demo <span>↗</span></Link><Link className="button ghost" href="#product-suite">Explore platform <span>↓</span></Link></div><div className="sales-hero-proof" role="group" aria-label="Published REOS products">{products.map((product) => <span key={product.slug}><i>{String(product.number).padStart(2, "0")}</i><b>{product.name}</b><ProductMaturityBadge maturity={product.maturity} /></span>)}</div></div><PlatformHeroPreview products={productAccess} /></section>

    <section className="section-pad platform-lifecycle" id="lifecycle"><SectionIntro label="THE PROPERTY LIFECYCLE" title={<>One Connected<br /><em>Property Lifecycle.</em></>} copy="REOS products connect specific workflows to the wider property context. Expand or hover on a stage to see its stakeholder function, workflow and system boundary." /><div className="platform-lifecycle-flow" aria-label="Property lifecycle coverage">{lifecycle.map(([number, name, owner, workflow, system], index) => <details key={name} open={index === 5}><summary><span>{number}</span><b>{name}</b><i>+</i></summary><dl><div><dt>Department</dt><dd>{owner}</dd></div><div><dt>Workflow</dt><dd>{workflow}</dd></div><div><dt>System</dt><dd>{system}</dd></div></dl></details>)}</div></section>

    <section className="section-pad platform-suite" id="product-suite"><SectionIntro label="REOS PLATFORM SUITE" title={<>One Platform.<br /><em>Multiple Automations.</em></>} copy="Two products have published maturity states. Four planned capabilities show the suite direction and are not represented as operationally available." /><div className="platform-suite-grid">{productAccess.map((product) => <article key={product.slug} id={product.slug} className="is-published"><header><span>{String(product.number).padStart(2, "0")}</span><ProductMaturityBadge maturity={product.maturity} /></header><small>{product.category}</small><h3>{product.name}</h3><p>{product.summary}</p><dl><div><dt>For</dt><dd>{product.primaryBuyer}</dd></div><div><dt>Capabilities</dt><dd>{product.capabilities.join(" · ")}</dd></div><div><dt>Outcome</dt><dd>{product.workflowResult}</dd></div></dl><div className="platform-suite-actions"><Link href={product.accessHref}>View product gateway <span>↗</span></Link><Link href={`${L("/demo")}?product=${product.slug}`}>Request demo</Link></div></article>)}{plannedProducts.map(([number, name, category, copy, audience, capabilities]) => <article key={name} className="is-planned"><header><span>{number}</span><ProductMaturityBadge maturity="Coming Soon" /></header><small>{category}</small><h3>{name}</h3><p>{copy}</p><dl><div><dt>Designed for</dt><dd>{audience}</dd></div><div><dt>Capabilities</dt><dd>{capabilities}</dd></div><div><dt>Boundary</dt><dd>Planned capability; scope, integrations and availability require validation.</dd></div></dl><div className="platform-suite-actions"><Link href={`${L("/demo")}?intent=${encodeURIComponent(`Discuss planned capability: ${name}`)}`}>Discuss the use case <span>↗</span></Link></div></article>)}</div><ProductMaturityLegend /></section>

    <section className="section-pad platform-fragmentation"><SectionIntro label="WHY PROPERTY OPERATIONS FAIL" title={<>Traditional Property Operations<br /><em>Are Fragmented.</em></>} copy="The process may be known, but its evidence, approvals, systems and customer communications are often managed separately." /><div>{fragmentation.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><b>{item}</b><i aria-hidden="true">{index < fragmentation.length - 1 ? "→" : "!"}</i></article>)}</div></section>
    <section className="section-pad platform-before-after"><SectionIntro label="THE REOS TRANSFORMATION" title={<>One Workflow.<br /><em>One Truth.</em></>} copy="Compare traditional coordination with a controlled operating model that connects evidence, ownership and handoffs." /><BeforeAfterWorkflow /></section>
    <section className="section-pad sales-how" id="product-experience"><SectionIntro label="HOW THE PRODUCTS WORK" title={<>From case opened.<br /><em>To outcome prepared.</em></>} copy="Step through the two published workflows. REOS guides and records the work; authorized people and official systems retain their required authority." /><ProductWorkflowDemo /></section>
    <section className="section-pad platform-screens"><SectionIntro label="PLATFORM EXPERIENCE" title={<>See the work.<br /><em>Not a decorative promise.</em></>} copy="Explore illustrative product screens for case coordination, workflow review and governance. Concept screens are explicitly separated from published product maturity." /><PlatformScreenGallery /></section>

    <section className="section-pad platform-stakeholder-value"><SectionIntro label="WHO BENEFITS" title={<>Built For<br /><em>Every Participant.</em></>} copy="Each participant receives the context required for their role while shared workflow and authority boundaries stay protected." /><div>{stakeholderValue.map(([name, problem, solution, benefit], index) => <article key={name}><span>{String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><small>Current problem</small><p>{problem}</p><small>REOS solution</small><p>{solution}</p><small>Business benefit</small><p>{benefit}</p></article>)}</div><Link className="text-link" href={L("/stakeholders")}>Explore all 12 stakeholder groups <span>↗</span></Link></section>

    <section className="section-pad platform-governance-engine"><div><span className="eyebrow">GOVERNANCE ENGINE</span><h2>Built For<br /><em>Control.</em></h2><p>REOS coordinates workflow and evidence within declared boundaries. It does not replace the decisions of authorities, authorized users or systems of record.</p><div className="hero-actions"><Link className="button gold" href={L("/trust-centre")}>Review the Trust Centre <span>↗</span></Link><Link className="button ghost" href={L("/platform/evaluation")}>Plan an evaluation</Link></div></div><div className="platform-governance-grid">{governance.map(([number, title, copy]) => <article key={title}><span>{number}</span><b>{title}</b><p>{copy}</p></article>)}</div></section>
    <section className="section-pad platform-business-outcomes"><SectionIntro label="MEASURABLE BUSINESS VALUE" title={<>Results<br /><em>That Matter.</em></>} copy="Outcome areas are stated without unsupported percentages or guaranteed processing claims; measurable targets are agreed during evaluation." /><div>{outcomes.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="sales-final-cta"><span className="eyebrow">SEE REOS IN YOUR WORKFLOW</span><h2>Bring Property Operations<br /><em>Into One Connected System.</em></h2><p>Transform title deeds, NOCs, handovers and property workflows through a single governed platform.</p><div className="hero-actions"><Link className="button gold" href={L("/demo")}>Request a demo <span>↗</span></Link><Link className="button ghost" href={`${L("/demo")}?intent=Product%20walkthrough`}>Talk to REOS experts</Link></div></section>
  </Page>;
}

export default function PlatformPage() { return <View locale={DEFAULT_LOCALE} />; }
