import type { Metadata } from "next";
import Link from "next/link";
import { BeforeAfterWorkflow, PlatformHeroPreview, PlatformScreenGallery, ProductWorkflowDemo } from "../components/PlatformProductExperience";
import { Page, SectionIntro } from "../components/SiteShell";
import { products } from "../data/products";
import { DEFAULT_LOCALE, localePath, type Locale } from "../i18n/config";
import { ProductMaturityBadge, ProductMaturityLegend } from "../components/Governance";

export const metadata: Metadata = { title: "Property Workflow Products & Operating System | REOS", description: "Explore governed REOS property workflow products across the development lifecycle." };

const lifecycle = [
  ["01", "Plot", "Development", "Establish land and ownership context", "Land and authority records"], ["02", "Project", "Development", "Coordinate readiness and approvals", "Project and planning systems"],
  ["03", "Unit", "Development", "Create the controlled unit record", "Development systems"], ["04", "Sales", "Commercial", "Connect buyer, unit, terms and evidence", "CRM and sales systems"],
  ["05", "Handover", "Customer operations", "Prepare inspection, evidence and acceptance", "Handover systems"], ["06", "Title Deed", "Registration", "Prepare registration-ready evidence", "Authorized registry"],
  ["07", "NOC", "Approvals", "Resolve prerequisites and issuer requirements", "Authorized issuer"], ["08", "Resale", "Transactions", "Coordinate ownership and clearance readiness", "Transaction systems"],
  ["09", "Cancellation", "Commercial governance", "Control approvals, refunds and inventory release", "Finance and sales systems"], ["10", "Operations", "Community operations", "Connect service, occupancy and asset context", "Property systems"],
] as const;

const plannedProducts = [
  ["03", "Unit Cancellation", "Sales & inventory", "Control cancellation requests, approvals, refund evidence, inventory release and decision history.", "Developers · Finance · Sales operations"],
  ["04", "Customer Handover", "Customer operations", "Coordinate inspections, snagging, handover evidence, customer acceptance and key release.", "Developers · Owners · Community operators"],
  ["05", "AI Document Intelligence", "Evidence readiness", "Planned document classification, extraction, completeness review and exception guidance within governed workflows.", "Operations · Reviewers · Compliance teams"],
  ["06", "Enterprise Integration Layer", "Orchestration", "Planned adapters and workflow orchestration across approved enterprise and authority boundaries.", "Enterprise IT · Operations · Authorized parties"],
] as const;

const stakeholderValue = [
  ["Developers", "Fragmented project-to-customer handoffs", "Coordinate lifecycle cases and evidence"], ["Authorities", "Unstructured or incomplete submissions", "Receive clearer, traceable case context"],
  ["Agencies", "Limited transaction readiness visibility", "See requirements, status and next owner"], ["Property owners", "Unclear progress and responsibilities", "Follow a guided, visible case journey"],
  ["Investors", "Portfolio information spread across teams", "Review governed operational context"], ["Banks", "Evidence and dependency uncertainty", "Understand case readiness and boundaries"],
  ["Consultants", "Repeated clarification and document chasing", "Work from shared requirements and versions"], ["Contractors", "Disconnected approvals and delivery evidence", "Connect actions to the correct project context"],
  ["Community operators", "Handover and service records arrive late", "Prepare operational context earlier"],
] as const;

const governance = [["01", "Permissions", "Role and organization boundaries"], ["02", "Workflow", "Defined states, owners and handoffs"], ["03", "Evidence", "Documents connected to each case"], ["04", "Approvals", "Authorized review and decision paths"], ["05", "Audit", "Versions, actions and history"], ["06", "Integration", "Explicit system and authority boundaries"], ["07", "Governance", "Maturity, scope and acceptance controls"]] as const;
const outcomes = [["Clear accountability", "Every active action has an owner, reason and next handoff."], ["Operational visibility", "Participants see the same case state and dependencies."], ["Earlier readiness", "Missing evidence can surface before the next critical gate."], ["Governed execution", "Actions and decisions remain connected to their supporting context."], ["Connected lifecycle", "Products operate within one property journey rather than isolated screens."], ["Audit confidence", "Evidence, versions and decisions remain reviewable through workflow history."]] as const;

export function View({ locale = DEFAULT_LOCALE }: { locale?: Locale }) {
  const L = (path: string) => localePath(locale, path);
  const productAccess = products.map((product) => ({ ...product, accessHref: L(`/platform/products/${product.slug}/login`) }));
  return <Page className="inner-page" locale={locale}>
    <section className="sales-hero platform-commercial-hero"><div className="sales-hero-copy"><span className="eyebrow">REOS PRODUCT PLATFORM · B2B · B2G · B2C</span><h1>The Operating System<br /><em>for Modern Property Development.</em></h1><p>REOS connects property workflows, stakeholders, evidence and decisions across the development lifecycle—then applies that operating model through governed, licence-controlled products.</p><div className="hero-actions"><Link className="button gold" href={L("/demo")}>Request a demo <span>↗</span></Link><Link className="button ghost" href="#product-suite">Explore products <span>↓</span></Link></div><div className="sales-hero-proof" role="group" aria-label="Published REOS products">{products.map((product) => <span key={product.slug}><i>{String(product.number).padStart(2, "0")}</i><b>{product.name}</b><ProductMaturityBadge maturity={product.maturity} /></span>)}</div></div><PlatformHeroPreview products={productAccess} /></section>

    <section className="section-pad platform-lifecycle" id="lifecycle"><SectionIntro label="THE PROPERTY LIFECYCLE" title={<>One operating layer.<br /><em>Across the asset lifecycle.</em></>} copy="REOS products connect specific workflows to the wider property context. Expand a stage to see its operating responsibility and system boundary." /><div className="platform-lifecycle-flow" aria-label="Property lifecycle coverage">{lifecycle.map(([number, name, owner, workflow, system], index) => <details key={name} open={index === 5}><summary><span>{number}</span><b>{name}</b><i>+</i></summary><dl><div><dt>Function</dt><dd>{owner}</dd></div><div><dt>Workflow</dt><dd>{workflow}</dd></div><div><dt>Boundary</dt><dd>{system}</dd></div></dl></details>)}</div></section>

    <section className="section-pad platform-suite" id="product-suite"><SectionIntro label="REOS PRODUCT SUITE" title={<>Start with the workflow.<br /><em>Expand through one platform.</em></>} copy="Two products have published maturity states. Four planned capabilities show the suite direction and are not represented as operationally available." /><div className="platform-suite-grid">{productAccess.map((product) => <article key={product.slug} id={product.slug} className="is-published"><header><span>{String(product.number).padStart(2, "0")}</span><ProductMaturityBadge maturity={product.maturity} /></header><small>{product.category}</small><h3>{product.name}</h3><p>{product.summary}</p><dl><div><dt>For</dt><dd>{product.primaryBuyer}</dd></div><div><dt>Outcome</dt><dd>{product.workflowResult}</dd></div></dl><div className="platform-suite-actions"><Link href={product.accessHref}>View product gateway <span>↗</span></Link><Link href={`${L("/demo")}?product=${product.slug}`}>Request demo</Link></div></article>)}{plannedProducts.map(([number, name, category, copy, audience]) => <article key={name} className="is-planned"><header><span>{number}</span><ProductMaturityBadge maturity="Coming Soon" /></header><small>{category}</small><h3>{name}</h3><p>{copy}</p><dl><div><dt>Designed for</dt><dd>{audience}</dd></div><div><dt>Boundary</dt><dd>Planned capability; scope, integrations and availability require validation.</dd></div></dl><div className="platform-suite-actions"><Link href={`${L("/demo")}?intent=${encodeURIComponent(`Discuss planned capability: ${name}`)}`}>Discuss the use case <span>↗</span></Link></div></article>)}</div><ProductMaturityLegend /></section>

    <section className="section-pad platform-before-after"><SectionIntro label="WHY REOS" title={<>From fragmented coordination.<br /><em>To one controlled case state.</em></>} copy="Compare how the work around a property process changes when evidence, ownership and handoffs are connected." /><BeforeAfterWorkflow /></section>
    <section className="section-pad sales-how" id="product-experience"><SectionIntro label="HOW THE PRODUCTS WORK" title={<>From case opened.<br /><em>To outcome prepared.</em></>} copy="Step through the two published workflows. REOS guides and records the work; authorized people and official systems retain their required authority." /><ProductWorkflowDemo /></section>
    <section className="section-pad platform-screens"><SectionIntro label="PLATFORM EXPERIENCE" title={<>See the work.<br /><em>Not a decorative promise.</em></>} copy="Explore illustrative product screens for case coordination, workflow review and governance. Concept screens are explicitly separated from published product maturity." /><PlatformScreenGallery /></section>

    <section className="section-pad platform-stakeholder-value"><SectionIntro label="WHO USES REOS" title={<>Different responsibilities.<br /><em>One operating context.</em></>} copy="Each participant receives the context required for their role while shared workflow and authority boundaries stay protected." /><div>{stakeholderValue.map(([name, problem, benefit], index) => <article key={name}><span>{String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><small>Current friction</small><p>{problem}</p><small>REOS value</small><p>{benefit}</p></article>)}</div><Link className="text-link" href={L("/stakeholders")}>Explore all 12 stakeholder groups <span>↗</span></Link></section>

    <section className="section-pad platform-governance-engine"><div><span className="eyebrow">GOVERNANCE ENGINE</span><h2>Control built into<br /><em>the operating model.</em></h2><p>REOS coordinates workflow and evidence within declared boundaries. It does not replace the decisions of authorities, authorized users or systems of record.</p><div className="hero-actions"><Link className="button gold" href={L("/trust-centre")}>Review the Trust Centre <span>↗</span></Link><Link className="button ghost" href={L("/platform/evaluation")}>Plan an evaluation</Link></div></div><div className="platform-governance-grid">{governance.map(([number, title, copy]) => <article key={title}><span>{number}</span><b>{title}</b><p>{copy}</p></article>)}</div></section>
    <section className="section-pad platform-business-outcomes"><SectionIntro label="BUSINESS OUTCOMES" title={<>What changes<br /><em>operationally?</em></>} copy="REOS is designed to make complex property work more visible, structured and accountable without unsupported performance claims." /><div>{outcomes.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="sales-final-cta"><span className="eyebrow">SEE REOS IN YOUR WORKFLOW</span><h2>Bring the process.<br /><em>See the operating model.</em></h2><p>Choose a product walkthrough or bring a workflow for a scoped evaluation. We will clarify maturity, boundaries, evidence and the next decision before any pilot commitment.</p><div className="hero-actions"><Link className="button gold" href={L("/demo")}>Request a demo <span>↗</span></Link><Link className="button ghost" href={L("/platform/evaluation")}>Explore the evaluation path</Link></div></section>
  </Page>;
}

export default function PlatformPage() { return <View locale={DEFAULT_LOCALE} />; }
