import type { Metadata } from "next";
import Link from "next/link";
import { BeforeAfterWorkflow, PlatformHeroPreview, PlatformScreenGallery } from "../components/PlatformProductExperience";
import { PlatformLifecycleExplorer } from "../components/PlatformLifecycleExplorer";
import { Page, SectionIntro } from "../components/SiteShell";
import { products } from "../data/products";
import { DEFAULT_LOCALE, localePath, type Locale } from "../i18n/config";
import { ProductMaturityBadge, ProductMaturityLegend } from "../components/Governance";

export const metadata: Metadata = { title: "Property Workflow Products & Operating System | REOS", description: "Explore governed REOS property workflow products across the development lifecycle." };

const plannedProducts = [
  ["03", "Unit Cancellation", "Sales & inventory", "Govern ownership reversals, cancellations and settlements using controlled workflows.", "Developers · Finance · Sales operations", "Compliance checks · Financial approvals · Authority coordination · Exception handling"],
  ["04", "Customer Handover", "Customer operations", "Streamline customer onboarding, inspection, snagging, acceptance and unit handover.", "Developers · Owners · Community operators", "Inspection readiness · Snagging · Customer acceptance · Key release"],
  ["05", "AI Document Intelligence", "Evidence readiness", "Extract, validate and govern documents using planned AI-assisted controls.", "Operations · Reviewers · Compliance teams", "Classification · Extraction · Completeness review · Exception guidance"],
  ["06", "Enterprise Integration Layer", "Orchestration", "Connect approved enterprise, authority and third-party systems through validated interfaces.", "Enterprise IT · Operations · Authorized parties", "Planned adapters · Case synchronization · Boundary controls · Integration monitoring"],
] as const;

const stakeholderValue = [
  ["Developers", "Fragmented project-to-customer handoffs", "Coordinate lifecycle cases", "More accountable delivery"],
  ["Sales teams", "Customer and unit status live in separate views", "Connect sales actions to case readiness", "Clearer transaction progress"],
  ["CRM teams", "Follow-up depends on manual status chasing", "Expose the current owner and next action", "More consistent customer service"],
  ["Customer care", "Customers receive incomplete progress context", "Share governed milestones and requirements", "Better-informed conversations"],
  ["Finance", "Refunds and clearances are disconnected from workflow", "Connect financial review to the case", "Controlled commercial decisions"],
  ["Legal", "Authority and evidence context is difficult to reconstruct", "Preserve versions, approvals and boundaries", "Stronger reviewability"],
  ["Property management", "Handover and operating records arrive late", "Prepare operational context earlier", "Smoother operational readiness"],
  ["Authorities", "Submissions can be unstructured or incomplete", "Prepare clearer, traceable case context", "Better submission readiness"],
  ["Property owners", "Progress and responsibilities are unclear", "Provide a guided, visible case journey", "Greater service clarity"],
  ["Investors", "Portfolio context is spread across teams", "Present governed operational visibility", "More informed oversight"],
] as const;

const governance = [["01", "Policy enforcement", "Workflow rules applied within the agreed scope"], ["02", "Approval matrix", "Defined reviewers, approvers and handoffs"], ["03", "Authority controls", "Explicit decision and system boundaries"], ["04", "Compliance rules", "Required checks connected to workflow"], ["05", "Exception monitoring", "Incomplete and blocked cases made visible"], ["06", "Risk controls", "Sensitive actions kept within authorized roles"], ["07", "Audit trails", "Versions, actions and decisions preserved"]] as const;
const outcomes = [["Title deed readiness", "Prepare evidence and ownership actions through one controlled case."], ["NOC readiness", "Make prerequisites, issuer context and outstanding actions visible."], ["Customer experience", "Give service teams clearer milestones and next actions."], ["Operational visibility", "See case state, dependencies and responsibility across participants."], ["Reduced manual coordination", "Replace avoidable status chasing with guided workflow context."], ["Governed transactions", "Keep reviews and decisions connected to supporting evidence."], ["Reduced operational risk", "Surface exceptions and boundaries before work progresses."], ["Business scalability", "Apply one operating model across additional governed workflows."]] as const;

export function View({ locale = DEFAULT_LOCALE }: { locale?: Locale }) {
  const L = (path: string) => localePath(locale, path);
  const productAccess = products.map((product) => ({ ...product, accessHref: L(`/platform/products/${product.slug}/login`) }));
  return <Page className="inner-page" locale={locale}>
    <section className="sales-hero platform-commercial-hero"><div className="sales-hero-copy"><span className="eyebrow">REOS PROPERTY OPERATING SYSTEM</span><h1>The Operating System<br /><em>for Modern Property Development</em></h1><p>Connect property workflows from plot and unit readiness through governed title deed coordination, NOC processing and ongoing property operations.</p><div className="platform-flagship-line"><b>Title Deed Automation</b><ProductMaturityBadge maturity="Early Access" /></div><div className="hero-actions"><Link className="button gold" href={`${L("/demo")}?product=title-deed-automation`}>Request Title Deed Demo <span>↗</span></Link><Link className="button ghost" href="#lifecycle">Explore the Platform <span>↓</span></Link></div></div><PlatformHeroPreview products={productAccess.filter((product) => product.slug === "title-deed-automation")} /></section>

    <section className="section-pad platform-lifecycle" id="lifecycle"><SectionIntro label="THE PROPERTY LIFECYCLE" title={<>One Connected<br /><em>Property Lifecycle.</em></>} copy="Select any permanently labelled stage to discover its workflow, participants, supporting capability, maturity, boundary and related product experience." /><PlatformLifecycleExplorer demoHref={L("/demo")} /></section>

    <section className="section-pad platform-suite" id="product-suite"><SectionIntro label="REOS PLATFORM SUITE" title={<>One Platform.<br /><em>Multiple Automations.</em></>} copy="Title Deed Automation is available for Early Access evaluation. Five planned capabilities show the controlled product direction and are not presented as live operational products." /><div className="platform-suite-grid">{productAccess.map((product) => <article key={product.slug} id={product.slug} className={product.slug === "title-deed-automation" ? "is-flagship" : "is-planned"}><header><span>{String(product.number).padStart(2, "0")}</span><ProductMaturityBadge maturity={product.maturity} /></header><small>{product.category}</small><h3>{product.name}</h3><p>{product.summary}</p><dl><div><dt>For</dt><dd>{product.primaryBuyer}</dd></div><div><dt>Capabilities</dt><dd>{product.capabilities.join(" · ")}</dd></div><div><dt>Boundary</dt><dd>{product.slug === "title-deed-automation" ? "REOS coordinates workflow and evidence; official review and decisions remain with authorized people and systems." : "Planned capability; scope, integrations and availability require validation."}</dd></div></dl><div className="platform-suite-actions">{product.slug === "title-deed-automation" ? <><Link href={`${L("/demo")}?product=${product.slug}`}>Request Title Deed Demo <span>↗</span></Link><Link href={product.accessHref}>Existing licensed user</Link></> : <Link href={`${L("/demo")}?intent=${encodeURIComponent("Discuss planned capability: NOC Automation")}`}>Discuss planned capability <span>↗</span></Link>}</div></article>)}{plannedProducts.map(([number, name, category, copy, audience, capabilities]) => <article key={name} className="is-planned"><header><span>{number}</span><ProductMaturityBadge maturity="Coming Soon" /></header><small>{category}</small><h3>{name}</h3><p>{copy}</p><dl><div><dt>Designed for</dt><dd>{audience}</dd></div><div><dt>Capabilities</dt><dd>{capabilities}</dd></div><div><dt>Boundary</dt><dd>Planned capability; scope, integrations and availability require validation.</dd></div></dl><div className="platform-suite-actions"><Link href={`${L("/demo")}?intent=${encodeURIComponent(`Discuss planned capability: ${name}`)}`}>Discuss planned capability <span>↗</span></Link></div></article>)}</div><ProductMaturityLegend /></section>

    <section className="section-pad platform-before-after"><SectionIntro label="FROM FRAGMENTATION TO CONTROL" title={<>One Workflow.<br /><em>One Truth.</em></>} copy="See how a governed case replaces scattered evidence, unclear ownership, late exceptions and fragmented history without replacing authorized decisions." /><BeforeAfterWorkflow /></section>
    <section className="section-pad platform-screens"><SectionIntro label="PLATFORM EXPERIENCE" title={<>See the work.<br /><em>Not a decorative promise.</em></>} copy="Explore illustrative product screens for case coordination, workflow review and governance. Concept screens are explicitly separated from published product maturity." /><PlatformScreenGallery /></section>

    <section className="section-pad platform-stakeholder-value"><SectionIntro label="WHO BENEFITS" title={<>Built For<br /><em>Every Participant.</em></>} copy="Each participant receives the context required for their role while shared workflow and authority boundaries stay protected." /><div>{stakeholderValue.map(([name, problem, solution, benefit], index) => <article key={name}><span>{String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><small>Current problem</small><p>{problem}</p><small>REOS solution</small><p>{solution}</p><small>Business benefit</small><p>{benefit}</p></article>)}</div><Link className="text-link" href={L("/stakeholders")}>Explore all 12 stakeholder groups <span>↗</span></Link></section>

    <section className="section-pad platform-governance-engine"><div><span className="eyebrow">GOVERNANCE ENGINE</span><h2>Built For<br /><em>Control.</em></h2><p>REOS coordinates workflow and evidence within declared boundaries. It does not replace the decisions of authorities, authorized users or systems of record.</p><div className="hero-actions"><Link className="button gold" href={L("/trust-centre")}>Review the Trust Centre <span>↗</span></Link><Link className="button ghost" href={L("/platform/evaluation")}>Plan an evaluation</Link></div></div><div className="platform-governance-grid">{governance.map(([number, title, copy]) => <article key={title}><span>{number}</span><b>{title}</b><p>{copy}</p></article>)}</div></section>
    <section className="section-pad platform-business-outcomes"><SectionIntro label="MEASURABLE BUSINESS VALUE" title={<>Results<br /><em>That Matter.</em></>} copy="Outcome areas are stated without unsupported percentages or guaranteed processing claims; measurable targets are agreed during evaluation." /><div>{outcomes.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="sales-final-cta"><span className="eyebrow">START WITH THE FLAGSHIP EXPERIENCE</span><h2>Coordinate Title Deed Readiness<br /><em>Through One Governed Case.</em></h2><p>Evaluate Title Deed Automation in Early Access, or discuss how a planned capability could fit your operating context.</p><div className="hero-actions"><Link className="button gold" href={`${L("/demo")}?product=title-deed-automation`}>Request Title Deed Demo <span>↗</span></Link><Link className="button ghost" href={`${L("/demo")}?intent=Discuss%20a%20planned%20capability`}>Discuss a planned capability</Link></div></section>
  </Page>;
}

export default function PlatformPage() { return <View locale={DEFAULT_LOCALE} />; }
