import Link from "next/link";
import { Phase1Starter } from "./components/Phase1Starter";
import { Page, SectionIntro } from "./components/SiteShell";
import { journeys, roles } from "./data/phase1";

export default function Home(){return <Page className="home">
  <section className="hero"><div className="hero-image" aria-hidden="true"/><div className="hero-grid" aria-hidden="true"/><div className="hero-content"><span className="eyebrow">REOS COPILOT · DUBAI PHASE 1</span><h1>Know your next move<br/><em>in Dubai property.</em></h1><p>Tell REOS where the property is, who you are and what you want to accomplish. Get the journey, parties, evidence, dependencies and next action.</p><div className="hero-actions"><Link className="button gold" href="/#start">Start my journey <span>↗</span></Link><Link className="button ghost" href="/#how">How it works</Link></div></div><div className="hero-arch" aria-hidden="true"><div className="arch-light"/><div className="arch-copy"><span>01</span><b>WHERE</b><i>WHO</i><small>WHAT</small></div></div></section>
  <section className="journey-start section-pad" id="start"><SectionIntro label="START WITH YOUR GOAL" title={<>Where? Who are you?<br/><em>What do you want to do?</em></>} copy="Dubai is built now. Other emirates and professional stakeholder journeys are deliberately held for later stages rather than presented as finished guidance."/><Phase1Starter/></section>
  <section className="problem-section section-pad" id="how"><SectionIntro label="ONE GUIDED ROUTE" title={<>From fragmented portals<br/><em>to a clear next action.</em></>} copy="REOS does not replace an authority, bank, broker or adviser. It makes the customer journey understandable, connects the dependencies and points back to authoritative action."/><div className="promise-flow">{["Your goal","Journey stages","Parties & authorities","Evidence & dependencies","Next action"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b></div>)}</div></section>
  <section className="section-pad"><SectionIntro label="BUILT NOW" title={<>Three customer roles.<br/><em>Twelve practical journeys.</em></>} copy="Phase 1 prioritises the people making, completing and managing a Dubai property decision."/><div className="role-cards">{roles.map(r=><article key={r.id}><span>{r.name}</span><p>{r.copy}</p></article>)}</div><div className="goal-links">{journeys.map(j=><Link key={j.slug} href={`/journeys/${j.slug}`}><span>{j.title}</span><i>Open journey →</i></Link>)}</div></section>
  <section className="future-section section-pad"><div className="future-image" aria-hidden="true"/><div className="future-copy"><span className="eyebrow">CLEAR PRODUCT BOUNDARY</span><h2>Knowledge first.<br/><em>Execution later.</em></h2><p>Phase 1 is the free knowledge and navigation layer. Developer, broker, bank and authority workspaces—and other emirate rule sets—are architecture for later, not active journeys today.</p><Link className="button gold" href="/reos">See the roadmap <span>↗</span></Link></div><div className="pillar-list"><div><b>NOW</b><span>Dubai customer journeys</span></div><div><b>NEXT</b><span>Dubai professional depth</span></div><div><b>LATER</b><span>Other emirates, separately governed</span></div></div></section>
  </Page>}
